# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado/cv32e40p-vivado.cache/wt [current_project]
set_property parent.project_path C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado/cv32e40p-vivado.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado/cv32e40p-vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/example_tb/core/custom/hello.mem
read_verilog -library xil_defaultlib -sv {
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_aligner.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/include/cv32e40p_pkg.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_alu.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_alu_div.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/include/cv32e40p_apu_core_pkg.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_apu_disp.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_compressed_decoder.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_controller.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_core.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_cs_registers.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/include/cv32e40p_fpu_pkg.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_decoder.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_ex_stage.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_ff_one.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_fifo.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_hwloop_regs.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_id_stage.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_if_stage.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_int_controller.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_load_store_unit.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_memory_wrapper.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_mult.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_obi_interface.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_pmp.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_popcnt.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_prefetch_buffer.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_prefetch_controller.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_register_file_ff.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_sleep_unit.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/fpga_tdp_ram.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/uart_tx.sv
  C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/rtl/cv32e40p_core_memory.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/constraints/cv32e40p_core.sdc
set_property used_in_implementation false [get_files C:/Users/mpakasa/Desktop/cv32e40p_project/cv32e40p-vivado_synthesis/constraints/cv32e40p_core.sdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cv32e40p_core_memory -part xc7a100tftg256-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cv32e40p_core_memory.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cv32e40p_core_memory_utilization_synth.rpt -pb cv32e40p_core_memory_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
